# Global options
baseurl = "https://causalinfo.github.io/NeurIPS2024"
canonifyurls = true
languagecode = "en"
theme = "crl-uai-2022-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "Parameter estimation and causal structure learning from observational time series data"
  title = "A workshop @ the 2024 NeurIPS Conference"
  subtitle = "December 14th & 15th 2024"
  author = "Joseph Janssen, Vincent Guan, Elina Robeva"
  description = "2024 NeurIPS workshop on 'Parameter estimation and causal structure learning from observational time series data
' "
  keywords = ["workshop", "causal inference", "information theory", "time series"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Organisers"
    url  = "/organisers"
    weight = 2
[[menu.main]]
    name = "Schedule and Format"
    url  = "/schedule-format"
    weight = 3
[[menu.main]]
    name = "Invited Speakers"
    url  = "/invited-speakers"
    weight = 4
[[menu.main]]
    name = "Slides and Recording"
    url  = "/slides-recording"
    weight = 5
