# Global options
baseurl = "https://causalinfo.github.io/SIAM2024"
canonifyurls = true
languagecode = "en"
theme = "crl-uai-2022-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "Learning From Data With Information Theory and Causal Inference"
  title = "A minisymposium @ the 2024 SIAM Annual Meeting"
  subtitle = "July 18th & 19th 2024"
  author = "Joseph Janssen, Vincent Guan, Elina Robeva"
  description = "2024 SIAM Annual Meeting minisymposium on 'Learning From Data With Information Theory and Causal Inference' "
  keywords = ["minisymposium", "causal inference", "information theory"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Organisers"
    url  = "/organisers"
    weight = 2
[[menu.main]]
    name = "Schedule and Format"
    url  = "/schedule-format"
    weight = 3
[[menu.main]]
    name = "Invited Speakers"
    url  = "/invited-speakers"
    weight = 4
[[menu.main]]
    name = "Slides and Recording"
    url  = "/slides-recording"
    weight = 5
